name: codebuild-buildspec-nodejs

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  buildimage:
    name: Hello build
    runs-on: 
      - codebuild-testcodebuild2buildspec-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
    - name: check nodejs
      run: |
        cat /etc/os-release
        node -v
    - name: Checkout
      uses: actions/checkout@v4
